### ISSUE TITLE
Failed to patch ISO

### ISSUE THREAD

**Issue by Floatingram** [NicholasMoser/GNTool#37] opened 2021-01-09 23:05 UTC
Hello Im following the youtube tutorial on patching SGNT4 however i keep getting the error "Failed to patch ISO" 
For whatever reason it wont let me share the error log here but this is the contents: 

Jan 09, 2021 2:39:12 PM com.github.nicholasmoser.gamecube.GameCubeISO exportFiles
INFO: Finished exporting files.
Jan 09, 2021 2:39:13 PM com.github.nicholasmoser.tools.ISOPatcher$1 call
SEVERE: Error Extracting ISO
java.io.IOException: No zip entries were found for file: C:\Users\Rober\Desktop\Patch.zip.zip
	at com.github.nicholasmoser@3.7/com.github.nicholasmoser.zip.PatchZip.patch(Unknown Source)
	at com.github.nicholasmoser@3.7/com.github.nicholasmoser.tools.ISOPatcher$1.call(Unknown Source)
	at com.github.nicholasmoser@3.7/com.github.nicholasmoser.tools.ISOPatcher$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Jan 09, 2021 2:44:58 PM com.github.nicholasmoser.gamecube.GameCubeISO exportFiles
INFO: Exporting files...
Jan 09, 2021 2:45:01 PM com.github.nicholasmoser.gamecube.GameCubeISO exportFiles
INFO: Finished exporting files.
Jan 09, 2021 2:45:01 PM com.github.nicholasmoser.tools.ISOPatcher$1 call
SEVERE: Error Extracting ISO
java.io.IOException: No zip entries were found for file: C:\Users\Rober\Desktop\Patch.zip
	at com.github.nicholasmoser@3.7/com.github.nicholasmoser.zip.PatchZip.patch(Unknown Source)
	at com.github.nicholasmoser@3.7/com.github.nicholasmoser.tools.ISOPatcher$1.call(Unknown Source)
	at com.github.nicholasmoser@3.7/com.github.nicholasmoser.tools.ISOPatcher$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Jan 09, 2021 2:46:59 PM com.github.nicholasmoser.gamecube.GameCubeISO exportFiles
INFO: Exporting files...
Jan 09, 2021 2:47:02 PM com.github.nicholasmoser.gamecube.GameCubeISO exportFiles
INFO: Finished exporting files.
Jan 09, 2021 2:47:02 PM com.github.nicholasmoser.tools.ISOPatcher$1 call
SEVERE: Error Extracting ISO
java.io.IOException: No zip entries were found for file: D:\Patch.zip
	at com.github.nicholasmoser@3.7/com.github.nicholasmoser.zip.PatchZip.patch(Unknown Source)
	at com.github.nicholasmoser@3.7/com.github.nicholasmoser.tools.ISOPatcher$1.call(Unknown Source)
	at com.github.nicholasmoser@3.7/com.github.nicholasmoser.tools.ISOPatcher$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Ive tried this a few different times with different file locations etc... and i cant figure it out

**Comment by NicholasMoser** [comment] 2021-01-20 04:47
Are you still encountering this issue?

The issue is either with your patch zip or SGNT4 ISO. Can you send me the patch zip on discord? You should be able to get my username if you ask around on the SGNT4 discord.

**Comment by NicholasMoser** [comment] 2021-03-30 01:53
Closing this issue, feel free to reopen if it's still a problem.

**Closed by NicholasMoser** 2021-03-30 01:53 UTC
