### ISSUE TITLE
Failing extracting "0000.FPK" from MONSTER HUNTER G (WII) Jap

### ISSUE THREAD

**Issue by dragonslayer619** [NicholasMoser/GNTool#166] opened 2024-10-23 20:37 UTC
Hello,

could you fix the issues unpacking "0000.fpk" file from MONSTER HUNTER G wii japanese?

 "wiisoftwarekeyboardsound.brsar"  is causing issues with the fpk

please

**Comment by NicholasMoser** [comment] 2024-10-24 18:06
Closing this, as it appears to be a duplicate of https://github.com/NicholasMoser/GNTool/issues/165

**Closed by NicholasMoser** 2024-10-24 18:06 UTC
