### ISSUE TITLE
Support for Little Endian FPKs

### ISSUE THREAD

**Issue by mitchellhumphrey** [NicholasMoser/GNTool#47] opened 2021-06-19 19:41 UTC

**Comment by NicholasMoser** [comment] 2021-07-27 01:48
Duplicate of https://github.com/NicholasMoser/GNTool/issues/50
Added in GNTool 3.12.0: https://github.com/NicholasMoser/GNTool/releases/tag/3.12.0

**Closed by NicholasMoser** 2021-07-27 01:48 UTC
